### ISSUE TITLE
win32, more processor family type could added

### ISSUE THREAD

**Issue by 0x01f7** [djberg96/sys-uname#3]
**Sys:Uname.machine** could not detect some processor family type, such as Intel Core™ i7-2760QM.

According to [Win32_Processor class], the method **Sys:Uname.machine** defined in file [windows/sys/uname] missing some type, see the list below:

+ 122, Efficeon™ TM8000 Family
+ 131, AMD Athlon™ 64 Processor Family
+ 132, AMD Opteron™ Processor Family
+ 198, Intel Core™ i7-2760QM
+ 203, G6
+ 204, z/Architecture Base

[Win32_Processor class]:https://msdn.microsoft.com/en-us/library/aa394373%28v=vs.85%29.aspx
[windows/sys/uname]:https://github.com/djberg96/sys-uname/blob/ffi/lib/windows/sys/uname.rb

**Comment by djberg96** [comment]
Yep, I should add more. Got a PR for me?
