### ISSUE TITLE
Does sys-uname follow Semantic versioning?

### ISSUE THREAD

**Issue by jspanjers** [djberg96/sys-uname#6]
For gems depending on sys-uname that want to add a pessimistic version constraint (e.g. '~> 1.0'), it is useful to know if sys-uname follows the semantic versioning scheme.

I tend to believe it is, but I cannot find it in the README.

**Comment by djberg96** [comment]
I can't say officially that I follow semantic versioning. For example, I released production versions with a version that was less than 1.0.0 for a long time.

But I think I follow it closely enough that you can add a pessimistic version constraint without fear of your code blowing up.
